<select id="Specialty" name="Specialty" style="width:270px"><option value="">Choose Specialty</option>
<option value="5">Allergy &amp; Immunology</option>
<option value="7">Anesthesiology</option>
<option value="10">Cardiology (IM)</option>
<option value="15">Certified Nurse Midwife</option>
<option value="12">Colon &amp; Rectal Surgery</option>
<option value="16">Critical Care Medicine</option>
<option value="20">Dentistry</option>
<option value="21">Dermatology</option>
<option value="27">Emergency Medicine</option>
<option value="29">Endocrinology&amp;Metabolism (IM)</option>
<option value="30">Endodontics</option>
<option value="34">Family Medicine</option>
<option value="167">Family Medicine (Sports Medicine)</option>
<option value="170">Female Pelvic Medicine</option>
<option value="36">Gastroenterology (IM)</option>
<option value="38">Genetics</option>
<option value="39">Geriatrics (Family Medicine)</option>
<option value="40">Geriatrics (Internal Medicine)</option>
<option value="49">Gynecologic Oncology (OB/GYN)</option>
<option value="51">Hand Surgery (Orthopedic Surg)</option>
<option value="53">Hematology-Oncology (IM)</option>
<option value="59">Infectious Disease (IM)</option>
<option value="58">Internal Medicine</option>
<option value="57">Interventional Cardiology</option>
<option value="63">Maternal-Fetal Med (OB/GYN)</option>
<option value="66">Neonatal-Perinatal Med (Peds)</option>
<option value="67">Nephrology (Internal Medicine)</option>
<option value="70">Neurology</option>
<option value="171">Neuropsychology</option>
<option value="71">Neurosurgery</option>
<option value="173">Nuclear Cardiology</option>
<option value="74">Obstetrics &amp; Gynecology</option>
<option value="136">Occupational Medicine</option>
<option value="83">Ophthalmology</option>
<option value="84">Oral &amp; Maxillofacial Surgery</option>
<option value="86">Orthodontics</option>
<option value="89">Orthopaedic Surgery</option>
<option value="31">Otolaryngology</option>
<option value="92">Pain Management</option>
<option value="91">Pain Mgmnt (Anesthesiology)</option>
<option value="94">Pathology</option>
<option value="95">Pediatric Cardiology</option>
<option value="96">Pediatric Critical Care Med</option>
<option value="97">Pediatric Dentistry</option>
<option value="98">Pediatric Dermatology</option>
<option value="103">Pediatric Endocrinology</option>
<option value="106">Pediatric Gastroenterology</option>
<option value="109">Pediatric Hematology-Oncology</option>
<option value="127">Pediatric Neurology</option>
<option value="134">Pediatric Pulmonology</option>
<option value="141">Pediatric Surgery</option>
<option value="115">Pediatrics</option>
<option value="121">Periodontics</option>
<option value="123">Physical Medicine &amp; Rehab</option>
<option value="125">Plastic Surgery</option>
<option value="128">Podiatry</option>
<option value="139">Prosthodontics</option>
<option value="143">Psychiatry</option>
<option value="142">Psychology</option>
<option value="144">Pulmonary Medicine (IM)</option>
<option value="149">Radiation Oncology</option>
<option value="146">Radiology</option>
<option value="151">Reproductive Endocrin (OB/GYN)</option>
<option value="152">Rheumatology (IM)</option>
<option value="155">Sleep Medicine</option>
<option value="157">Spine Surgery</option>
<option value="160">Surgery</option>
<option value="44">Thoracic Surgery</option>
<option value="164">Urology</option>
<option value="47">Vascular (Gnrl Surgery)</option>
</select>